version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - mean_network

  backend:
    image: anuj2529/mean-backend:latest
    container_name: mean-backend
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://mongodb:27017/dd_db
      PORT: 8080
    depends_on:
      - mongodb
    networks:
      - mean_network

  frontend:
    image: anuj2529/mean-frontend:latest
    container_name: mean-frontend
    restart: unless-stopped
    networks:
      - mean_network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - mean_network

volumes:
  mongo_data:

networks:
  mean_network:
    driver: bridge
